### ISSUE TITLE
gistie fails with ssl error

### ISSUE THREAD

**Issue by hargup** [vivekiitkgp/gistie#1]
Here's the traceback I got, this probably because I'm working behind a http proxy.

``` python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 552, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 314, in _get_conn
    return conn or self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 734, in _new_conn
    return self._prepare_conn(connection)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 701, in _prepare_conn
    connection.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 141, in connect
    self.assert_hostname or self.host)
  File "/usr/lib/python3/dist-packages/urllib3/packages/ssl_match_hostname/__init__.py", line 91, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
urllib3.packages.ssl_match_hostname.CertificateError: hostname '10.3.100.207' doesn't match either of '*.github.com', 'github.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: hostname '10.3.100.207' doesn't match either of '*.github.com', 'github.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gistie", line 124, in <module>
    exit(create_gist())
  File "/usr/local/bin/gistie", line 90, in create_gist
    data=json.dumps(payload))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname '10.3.100.207' doesn't match either of '*.github.com', 'github.com'
```

**Comment by raivivek** [comment]
I couldn't reproduce the error. It could possibly have been a network issue.
